In [7]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt

In [20]:
A = np.arange(1, 5).reshape((2, 2))
A

array([[1, 2],
       [3, 4]])

In [21]:
A.T

array([[1, 3],
       [2, 4]])

In [22]:
np.invert(A)

array([[-2, -3],
       [-4, -5]])

In [23]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
b = np.array([[5], [6]])
b

array([[5],
       [6]])

In [26]:
linalg.solve(A, b)

array([[-4. ],
       [ 4.5]])

In [27]:
linalg.det(A)

-2.0000000000000004